name: VNC Viewer
version: 1.6.0
slug: vnc
panel_icon: mdi:remote-desktop
description: 🚨 Addons are moved to https://github.com/Poeschl-HomeAssistant-Addons/repository
url: https://github.com/Poeschl/Hassio-Addons/tree/main/vnc-viewer
ingress: true
ingress_port: 6080
ingress_entry: vnc.html?autoconnect=true
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
boot: manual
hassio_api: true
image: ghcr.io/poeschl-homeassistant-addons/vnc-viewer-{arch}
init: false
options:
  vnc_server_host: localhost
schema:
  vnc_server_host: str
  vnc_server_port: int?
  vnc_server_password: str?
